version: 2.1

executors:
  executor:
    machine:
          image: ubuntu-1604:201903-01

jobs:
  build:
    executor: executor
    steps:
      - checkout
      - run:
          name: "Pull Submodules"
          command: |
            git submodule init
            git submodule update --remote
      - run:
          name: Build container
          command: make docker_build
      - run:
          name: Run tests
          command: make docker_test