name: pdqhash-python CI/CD

on: workflow_dispatch

jobs:
  build:
    name: Build Package
    strategy:
      matrix:
        python: ['3.7']
        os: [windows-latest]
    runs-on: ${{ matrix.os }}
    steps:
      - name: Checkout Code
        uses: actions/checkout@v3
        with:
          submodules: true
          fetch-depth: 0
      - name: Set up Python ${{ matrix.python }}
        id: python
        uses: actions/setup-python@v4
        with:
          python-version: ${{ matrix.python }}
      - name: Cache Environment
        uses: actions/cache@v3
        with:
          path: .venv
          key: ${{ runner.os }}-${{ steps.python.outputs.python-version }}
      - name: Initialize
        run: make init
      - name: Test
        run: make test
      - name: Package
        run: make package
      - uses: actions/upload-artifact@v3
        with:
          name: wheels
          path: dist/*