name: pdqhash-python CI/CD

on:
  push:
    branches: 
      - '**'

jobs:
  test:
    name: Test pdqhash-python
    strategy:
      matrix:
        python-version: [3.6]
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Code
        uses: actions/checkout@v2
      - name: Set up Python ${{ matrix.python-version }}
        uses: actions/setup-python@v2
        with:
          python-version: ${{ matrix.python-version }}
      - name: Install Pipenv
        run: |
          pip install pipenv
      - name: Make Host Environment
        run: |
          make init
      - name: Test Source
        run: |
          make test
